name: Playwright Tests with Github Actions

on:
  workflow_dispatch: {}

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run only runner files (sequential orchestrators)
      - name: Run Playwright tests
        run: npx playwright test runner.spec.js --reporter=list,html --output=playwright-report/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
